### PR TITLE
Arrow points to letter recipients, Player Animations

### PR DESCRIPTION
**Pull request by brimstonetrader**

### CODE REVIEW

**Comment by keyszl** [comment]
Also the camera movement needs more added to the boundary so the character stays moreso in the center (not sure if this is an issue already or addressed anywhere)

When you click the next button for the first NPC "name" it also makes your character move..

The done button doesn't close out of the dialogue.

**Comment by brimstonetrader** [comment]
These should be taken care of now. The player has a sound effect attached, which https://forum.unity.com/threads/hide-the-image-of-the-horn.13681/ seems to imply means it can't be helped unless you get rid of the sound altogether. I commented that out, but it can be easily put back in. Thank you for the feedback!

**Comment by keyszl** [comment]
Not sure if it's just on my end since unity was acting weird but I still can't click on next with the "name" npc once starting that dialogue

**Comment by brimstonetrader** [comment]
Can you be more specific? I don't know where the "name" npc is, and can't recreate a similar error on my end.

**Comment by brimstonetrader** [comment]
I saw something similar, I think it's because I had changed the cutscene script. Should work now.

**Comment by jonesamelia** [comment]
The player seems to move faster when clicking to move and the walk animation becomes blurry.

**Comment by jonesamelia** [comment]
I don't know if this makes sense but if you click somewhere and then try to walk in another direction using the keys the two movements fight each other and you have to wait until you get to the place you clicked. This doesn't happen in Ground Truth.

**Comment by brimstonetrader** [comment]
These two problems should be solved now.

**Comment by jonesamelia** [comment]
The circle that makes the player visible on the map is gone. The animal movement script is also giving a lot of errors.

**Comment by brimstonetrader** [comment]
I removed my edits to animal movement, and added the circle prefabs.

**Comment by keyszl** [comment]
Looooooooooooooks good to me!

**Pull request merged**
